version: "3.4"
services:
  csharp:
    build:
      context: .
    container_name: dot-net
    image: canopitu1/dot-net
    ports:
    - 5000:5000
    volumes:
    - ./src/:/work
    #working_dir: /work
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true
